CREATE TABLE Cities(
CityID INT NOT NULL PRIMARY KEY,
Name VARCHAR(50)
)	

CREATE TABLE Customers(
CustomerID INT NOT NULL PRIMARY KEY,
Name VARCHAR(50),
Birthday DATE,
CityID INT NOT NULL FOREIGN KEY REFERENCES Cities(CityID)
)

CREATE TABLE Orders(
OrderID INT NOT NULL PRIMARY KEY,
CustomerID INT NOT NULL FOREIGN KEY REFERENCES Customers(CustomerID)
)

CREATE TABLE ItemTypes(
ItemTypeID INT NOT NULL PRIMARY KEY,
Name VARCHAR(50)
)

CREATE TABLE Items(
ItemID INT NOT NULL PRIMARY KEY,
Name VARCHAR(50),
ItemTypeID INT NOT NULL FOREIGN KEY REFERENCES ItemTypes(ItemTypeID)
)

CREATE TABLE OrderItems(
OrderID INT NOT NULL,
ItemID INT NOT NULL
)

ALTER TABLE OrderItems
ADD CONSTRAINT pk_OrderItems PRIMARY KEY (OrderID, ItemID)

ALTER TABLE OrderItems
ADD CONSTRAINT fk_OrderItems_Items FOREIGN KEY (ItemID) REFERENCES Items(ItemID)

ALTER TABLE OrderItems
ADD CONSTRAINT fk_Items_OrderItems FOREIGN KEY (OrderID) REFERENCES Orders(OrderID)