ALTER TABLE Users
DROP CONSTRAINT PK_NEW

ALTER TABLE Users
ADD PRIMARY KEY (Id)

ALTER TABLE Users
ADD UNIQUE (Username)

ALTER TABLE Users
ADD CONSTRAINT MY_TABLE_USERNAME_LENGTH CHECK (DATALENGTH(Username) >=3) 