CREATE TABLE Towns
(
Id INT NOT NULL IDENTITY PRIMARY KEY,
Name NVARCHAR(50)
)

CREATE TABLE Addresses
(
Id INT NOT NULL IDENTITY PRIMARY KEY,
AdressText NVARCHAR(50),
TownId INT NOT NULL FOREIGN KEY REFERENCES Towns(Id)
)

CREATE TABLE Department
(
Id INT NOT NULL IDENTITY PRIMARY KEY,
Name NVARCHAR(50)
)

CREATE TABLE Employees
(
Id INT NOT NULL IDENTITY PRIMARY KEY,
FirstName NVARCHAR(50),
LastName NVARCHAR(50) NOT NULL,
JobTitle NVARCHAR(20) NOT NULL,
DepartmentId INT NOT NULL FOREIGN KEY REFERENCES Department(Id),
HireDate DATE NOT NULL,
Salary Decimal,
AddresId INT
)